apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-argocd
  template:
    metadata:
      labels:
        app: my-app-argocd
    spec:
      containers:
        - name: argocd
          image: localhost:5000/my_java_app:v1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: java-argocd-service
spec:
  selector:
    app:  my-app-argocd
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 8080
  type: ClusterIP